version: "3.9"

services:
  gateway:
    build: ./gateway
    image: gateway_service
    container_name: gateway_instance
    ports:
      - "8080:8080" # Mapping port 8080 from container to host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Allows container to interact with the host Docker daemon
    privileged: true # Required for managing Docker inside container
    networks:
      default_net:
        aliases:
          - gateway_alias

  db_coordinator:
    build: ./db_coordinator
    image: coordinator_service
    container_name: coordinator_instance
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Permits container to handle Docker daemon operations
    privileged: true # Necessary to enable Docker daemon access
    networks:
      default_net:
        aliases:
          - coordinator_alias

networks:
  default_net:
    name: public_network
